"use client";

import { useState } from "react";
import Link from "next/link";
import { CheckCircle2, Minus, ArrowRight } from "lucide-react";
import { CTASection } from "@/components/landing/CTASection";
import { Footer }     from "@/components/Footer";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://app.example.com";

// ── Data ───────────────────────────────────────────────────────────────────────

type Tier = {
  name:        string;
  tagline:     string;
  monthly:     number | null;
  annual:      number | null;
  cta:         string;
  ctaHref:     string;
  highlighted: boolean;
  features:    string[];
};

const TIERS: Tier[] = [
  {
    name:        "Free",
    tagline:     "Get started, no commitment",
    monthly:     0,
    annual:      0,
    cta:         "Start for free",
    ctaHref:     `${APP_URL}/auth/login?intent=signup`,
    highlighted: false,
    features: [
      "Pathway matching (top 3 results)",
      "Personalised eligibility checklist",
      "AI conversation in any language",
      "Canada pathway database",
      "Basic application timeline",
    ],
  },
  {
    name:        "Individual",
    tagline:     "For serious applicants",
    monthly:     29,
    annual:      19,
    cta:         "Get started",
    ctaHref:     `${APP_URL}/auth/login?intent=signup&plan=individual`,
    highlighted: true,
    features: [
      "Everything in Free",
      "Full pathway list (50+ matches)",
      "Complete editable checklist",
      "Document drafting (up to 5 docs)",
      "Application progress tracker",
      "Email support — 48h response",
      "Pathway updates when criteria change",
    ],
  },
  {
    name:        "Professional",
    tagline:     "For complex cases & employers",
    monthly:     79,
    annual:      59,
    cta:         "Get started",
    ctaHref:     `${APP_URL}/auth/login?intent=signup&plan=pro`,
    highlighted: false,
    features: [
      "Everything in Individual",
      "Unlimited document drafting",
      "Priority support — 24h response",
      "LMIA documentation assistance",
      "Licensed RCIC referral service",
      "Team seats (up to 5 members)",
      "Dedicated onboarding call",
    ],
  },
];

type CompRow = {
  feature:  string;
  free:     true | false | string;
  ind:      true | false | string;
  pro:      true | false | string;
};

const COMPARISON: CompRow[] = [
  { feature: "Pathway matching",          free: "Top 3",    ind: "50+",       pro: "50+"          },
  { feature: "AI conversation",           free: true,       ind: true,        pro: true           },
  { feature: "Personalised checklist",    free: "Read-only",ind: "Editable",  pro: "Editable"     },
  { feature: "Document drafting",         free: false,      ind: "5 docs",    pro: "Unlimited"    },
  { feature: "Progress tracker",          free: true,       ind: true,        pro: true           },
  { feature: "Email support",             free: false,      ind: "48h",       pro: "24h priority" },
  { feature: "LMIA support",              free: false,      ind: false,       pro: true           },
  { feature: "RCIC referral",             free: false,      ind: false,       pro: true           },
  { feature: "Team seats",                free: false,      ind: false,       pro: "Up to 5"      },
];

const FAQS = [
  {
    q: "Can I switch plans at any time?",
    a: "Yes. You can upgrade, downgrade, or cancel at any time from your account settings. If you downgrade mid-cycle, you keep access to paid features until the end of your billing period.",
  },
  {
    q: "Is there a free trial for paid plans?",
    a: "Yes — all paid plans include a 7-day free trial. No credit card required to start. You'll only be charged if you choose to continue after the trial ends.",
  },
  {
    q: "What counts as a 'document'?",
    a: "A document is any draft generated by Pathways — personal statements, cover letters, statutory declarations, and similar application documents. Checklists and timelines don't count toward this limit.",
  },
  {
    q: "Does the annual plan auto-renew?",
    a: "Yes, annual plans renew automatically at the end of the 12-month period. We'll send you a reminder email 30 days before renewal. You can cancel at any time before that.",
  },
  {
    q: "Is there a plan for immigration consultants?",
    a: "We're working on an Advisor plan for licensed RCICs and immigration lawyers who want to use Pathways with their clients. Contact us to join the early access waitlist.",
  },
];

// ── Components ────────────────────────────────────────────────────────────────

function FeatureRow({ value }: { value: true | false | string }) {
  if (value === true)
    return <CheckCircle2 size={17} className="text-green-deep mx-auto" aria-label="Included" />;
  if (value === false)
    return <Minus size={16} className="text-grey-300 mx-auto" aria-label="Not included" />;
  return <span className="text-sm text-grey-700 font-medium">{value}</span>;
}

function PricingToggle({
  annual,
  onToggle,
}: {
  annual: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="flex items-center gap-3 justify-center">
      <span className={`text-sm font-medium ${!annual ? "text-grey-900" : "text-grey-400"}`}>
        Monthly
      </span>
      <button
        onClick={onToggle}
        role="switch"
        aria-checked={annual}
        aria-label="Toggle annual billing"
        className={`relative w-11 h-6 rounded-full transition-colors duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-green-deep ${
          annual ? "bg-green-deep" : "bg-grey-300"
        }`}
      >
        <span
          className={`absolute top-[3px] left-[3px] w-[18px] h-[18px] rounded-full bg-white shadow transition-transform duration-200 ${
            annual ? "translate-x-5" : "translate-x-0"
          }`}
        />
      </button>
      <span className={`text-sm font-medium ${annual ? "text-grey-900" : "text-grey-400"}`}>
        Annual
        <span className="ml-2 text-xs font-semibold text-green-deep bg-green-tint px-2 py-0.5 rounded-full">
          Save ~35%
        </span>
      </span>
    </div>
  );
}

function PricingCard({
  tier,
  annual,
}: {
  tier: Tier;
  annual: boolean;
}) {
  const price = annual ? tier.annual : tier.monthly;

  return (
    <div
      className={`relative flex flex-col rounded-2xl p-8 ${
        tier.highlighted
          ? "bg-green-deep text-white ring-2 ring-green-deep"
          : "bg-white border border-grey-200"
      }`}
    >
      {tier.highlighted && (
        <div className="absolute -top-3.5 left-1/2 -translate-x-1/2">
          <span className="bg-white text-green-deep text-xs font-bold uppercase tracking-widest px-4 py-1.5 rounded-full shadow-card-md whitespace-nowrap">
            Most Popular
          </span>
        </div>
      )}

      <div className="mb-6">
        <p
          className={`text-xs font-semibold uppercase tracking-widest mb-1 ${
            tier.highlighted ? "text-white/60" : "text-green-deep"
          }`}
        >
          {tier.name}
        </p>
        <p className={`text-sm ${tier.highlighted ? "text-white/70" : "text-grey-500"}`}>
          {tier.tagline}
        </p>
      </div>

      {/* Price */}
      <div className="mb-8">
        {price === null ? (
          <p className={`font-display font-normal text-4xl leading-none ${tier.highlighted ? "text-white" : "text-grey-900"}`}>
            Custom
          </p>
        ) : price === 0 ? (
          <p className={`font-display font-normal text-4xl leading-none ${tier.highlighted ? "text-white" : "text-grey-900"}`}>
            Free
          </p>
        ) : (
          <div className="flex items-end gap-1.5">
            <p className={`font-display font-normal text-5xl leading-none tracking-tight ${tier.highlighted ? "text-white" : "text-grey-900"}`}>
              ${price}
            </p>
            <span className={`text-sm mb-1 ${tier.highlighted ? "text-white/60" : "text-grey-400"}`}>
              / month
            </span>
          </div>
        )}
        {annual && price !== null && price > 0 && (
          <p className={`text-xs mt-1.5 ${tier.highlighted ? "text-white/50" : "text-grey-400"}`}>
            Billed annually (${price * 12}/yr)
          </p>
        )}
      </div>

      {/* CTA */}
      <a
        href={tier.ctaHref}
        className={`flex items-center justify-center gap-2 font-semibold text-sm px-6 py-3 rounded-full min-h-[44px] mb-8 transition-all duration-150 active:scale-[0.98] ${
          tier.highlighted
            ? "bg-white text-green-deep hover:bg-green-tint"
            : "bg-green-deep text-white hover:bg-green-muted"
        }`}
      >
        {tier.cta} <ArrowRight size={15} aria-hidden="true" />
      </a>

      {/* Features */}
      <ul className="space-y-3 flex-1">
        {tier.features.map((f) => (
          <li key={f} className="flex items-start gap-3 text-sm">
            <CheckCircle2
              size={15}
              className={`mt-0.5 shrink-0 ${tier.highlighted ? "text-white/60" : "text-green-deep"}`}
              aria-hidden="true"
            />
            <span className={tier.highlighted ? "text-white/80" : "text-grey-600"}>
              {f}
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-grey-200">
      <button
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="w-full flex items-center justify-between text-left py-5 gap-4 group"
      >
        <span className={`font-medium text-base transition-colors ${open ? "text-green-deep" : "text-grey-900 group-hover:text-green-deep"}`}>
          {q}
        </span>
        <span className={`text-lg font-light shrink-0 transition-transform duration-200 ${open ? "rotate-45 text-green-deep" : "text-grey-400"}`}>
          +
        </span>
      </button>
      <div className={`overflow-hidden transition-all duration-300 ${open ? "max-h-64 opacity-100" : "max-h-0 opacity-0"}`}>
        <p className="text-grey-500 leading-relaxed text-sm pb-5 pr-8">{a}</p>
      </div>
    </div>
  );
}

// ── Page ───────────────────────────────────────────────────────────────────────

export default function PricingPage() {
  const [annual, setAnnual] = useState(true);

  return (
    <main>

      {/* ── Hero ─────────────────────────────────────────────────────── */}
      <section
        className="bg-green-deep pt-[calc(72px+5rem)] pb-24 max-md:pt-[calc(60px+3rem)] max-md:pb-16 text-center overflow-hidden relative"
        style={{
          backgroundImage:     "url('/textures/topo-lines.svg')",
          backgroundSize:      "600px 600px",
          backgroundRepeat:    "repeat",
          backgroundBlendMode: "overlay",
        }}
      >
        <div className="max-w-[1200px] mx-auto px-10 max-md:px-5 relative z-10">
          <p className="text-sm font-semibold tracking-widest uppercase text-white/50 mb-5">
            Pricing
          </p>
          <h1
            className="font-display font-normal text-white text-6xl max-md:text-4xl leading-tight tracking-tight mb-5"
            style={{ letterSpacing: "-0.02em", lineHeight: "1.1" }}
          >
            Simple, honest pricing.
          </h1>
          <p className="text-xl text-white/65 leading-relaxed max-w-md mx-auto">
            Start free. Pay only when you&apos;re ready to go further.
            No surprises, no hidden fees.
          </p>
        </div>
      </section>

      {/* ── Pricing cards ────────────────────────────────────────────── */}
      <section className="py-20 bg-grey-100 max-md:py-12">
        <div className="max-w-[1200px] mx-auto px-10 max-md:px-5">

          {/* Toggle */}
          <div className="mb-12">
            <PricingToggle annual={annual} onToggle={() => setAnnual((v) => !v)} />
          </div>

          {/* Cards */}
          <div className="grid grid-cols-3 gap-6 items-start max-lg:grid-cols-1 max-lg:max-w-md max-lg:mx-auto">
            {TIERS.map((tier) => (
              <PricingCard key={tier.name} tier={tier} annual={annual} />
            ))}
          </div>

          <p className="text-center text-xs text-grey-400 mt-8">
            All prices in CAD. 7-day free trial on all paid plans. Cancel anytime.
          </p>
        </div>
      </section>

      {/* ── Comparison table ─────────────────────────────────────────── */}
      <section className="py-24 bg-white max-md:py-14">
        <div className="max-w-[1200px] mx-auto px-10 max-md:px-5">
          <h2
            className="font-display font-normal text-4xl max-md:text-2xl text-grey-900 leading-tight tracking-tight mb-14"
            style={{ letterSpacing: "-0.02em" }}
          >
            Compare plans in detail.
          </h2>

          <div className="overflow-x-auto -mx-10 px-10 max-md:-mx-5 max-md:px-5">
            <table className="w-full min-w-[520px] border-collapse">
              <thead>
                <tr>
                  <th className="text-left pb-5 text-sm font-semibold text-grey-400 font-sans w-1/2" />
                  <th className="text-center pb-5 text-sm font-medium text-grey-500 w-[17%]">Free</th>
                  <th className="text-center pb-5 w-[17%]">
                    <span className="inline-block bg-green-deep text-white text-xs font-semibold px-3 py-1.5 rounded-full">
                      Individual
                    </span>
                  </th>
                  <th className="text-center pb-5 text-sm font-medium text-grey-500 w-[17%]">Professional</th>
                </tr>
              </thead>
              <tbody>
                {COMPARISON.map((row, i) => (
                  <tr
                    key={row.feature}
                    className={`border-t border-grey-100 ${i % 2 === 0 ? "bg-white" : "bg-grey-100/40"}`}
                  >
                    <td className="py-4 text-sm text-grey-700 font-medium pr-6">{row.feature}</td>
                    <td className="py-4 text-center"><FeatureRow value={row.free} /></td>
                    <td className="py-4 text-center"><FeatureRow value={row.ind} /></td>
                    <td className="py-4 text-center"><FeatureRow value={row.pro} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* ── Enterprise callout ───────────────────────────────────────── */}
      <section className="py-16 bg-green-tint border-y border-green-deep/10 max-md:py-12">
        <div className="max-w-[1200px] mx-auto px-10 max-md:px-5">
          <div className="flex items-center justify-between gap-8 max-md:flex-col max-md:text-center">
            <div>
              <p className="text-xs font-semibold uppercase tracking-widest text-green-deep mb-2">
                Enterprise
              </p>
              <h3 className="font-display font-normal text-3xl text-grey-900 leading-tight mb-2">
                Hiring international talent?
              </h3>
              <p className="text-grey-500 text-base leading-relaxed max-w-md">
                Custom plans for employers, staffing agencies, and RCICs managing
                multiple applicants. LMIA support, team management, and a dedicated account manager.
              </p>
            </div>
            <Link
              href="/contact"
              className="inline-flex items-center gap-2 bg-green-deep text-white font-semibold text-sm px-7 py-3.5 rounded-full min-h-[48px] hover:bg-green-muted active:scale-[0.98] transition-all duration-150 whitespace-nowrap shrink-0"
            >
              Talk to us <ArrowRight size={15} aria-hidden="true" />
            </Link>
          </div>
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────────────── */}
      <section className="py-24 bg-white max-md:py-14">
        <div className="max-w-[1200px] mx-auto px-10 max-md:px-5">
          <div className="grid grid-cols-[1fr_1.6fr] gap-20 max-lg:grid-cols-1 max-lg:gap-10">
            <div>
              <p className="text-sm font-semibold uppercase tracking-widest text-green-deep mb-4">
                FAQ
              </p>
              <h2
                className="font-display font-normal text-4xl text-grey-900 leading-tight tracking-tight mb-5"
                style={{ letterSpacing: "-0.02em" }}
              >
                Pricing questions.
              </h2>
              <p className="text-grey-500 leading-relaxed">
                Still have questions?{" "}
                <Link href="/contact" className="text-green-deep font-medium hover:underline">
                  Get in touch
                </Link>
                .
              </p>
            </div>
            <div className="max-w-[560px]">
              {FAQS.map((item) => (
                <FAQItem key={item.q} {...item} />
              ))}
            </div>
          </div>
        </div>
      </section>

      <CTASection />
      <Footer />
    </main>
  );
}
